// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZhuf-tVaBsOBdi_SgdPDH8RQMsLDs7ao',
    appId: '1:930797101948:web:c77215be84b4f679c67af9',
    messagingSenderId: '930797101948',
    projectId: 'bobo-b7385',
    authDomain: 'bobo-b7385.firebaseapp.com',
    storageBucket: 'bobo-b7385.firebasestorage.app',
    measurementId: 'G-LTLEK992L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP2hJN9Bz0bUpVv5dgrydys22SbbGR7Gc',
    appId: '1:930797101948:android:8e1c7cdf8ed6e919c67af9',
    messagingSenderId: '930797101948',
    projectId: 'bobo-b7385',
    storageBucket: 'bobo-b7385.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_cMhtjaUR8Ft_vJVeJH_Ffkw_YuYT9eo',
    appId: '1:930797101948:ios:75100e467ed87237c67af9',
    messagingSenderId: '930797101948',
    projectId: 'bobo-b7385',
    storageBucket: 'bobo-b7385.firebasestorage.app',
    iosBundleId: 'com.example.bobo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_cMhtjaUR8Ft_vJVeJH_Ffkw_YuYT9eo',
    appId: '1:930797101948:ios:75100e467ed87237c67af9',
    messagingSenderId: '930797101948',
    projectId: 'bobo-b7385',
    storageBucket: 'bobo-b7385.firebasestorage.app',
    iosBundleId: 'com.example.bobo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZhuf-tVaBsOBdi_SgdPDH8RQMsLDs7ao',
    appId: '1:930797101948:web:e650cdea0ed6a203c67af9',
    messagingSenderId: '930797101948',
    projectId: 'bobo-b7385',
    authDomain: 'bobo-b7385.firebaseapp.com',
    storageBucket: 'bobo-b7385.firebasestorage.app',
    measurementId: 'G-BL9K6K4P9G',
  );
}
